### ISSUE TITLE
[FR] LED RGB Support 

### ISSUE THREAD

**Issue by Benkeno** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#110]
Omg! This runs so smooth!! It's beauty. And I love my printer now!
I simply pushed the "Mega_X_v1.1.9.hex" into my stock Mega X. And "uugh awww"... It works perfect. 
Now I installed a "Neopixel" 8 Led inside the hotend for some ambient at night. 

Discovered the LED/RGB strip section is literally disabled. 
Is there a way to get the compiled hex with LED enabled? 
Would be great to see this glow 🙏

**Comment by knutwurst** [comment]
Many Thanks! <3 
Regarding the RGB thing: This is deliberately deactivated, because unfortunately you would not have the possibility to control it via the display. The firmware can handle RGB LED, but the display cannot :(
See: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/FAQ-(english)
