### ISSUE TITLE
[FR]Build for the 32-bit Trigorilla Pro version of i3 mega

### ISSUE THREAD

**Issue by Blue-Beaker** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#26]
### Description

Build for the 32-bit Trigorilla Pro version (also known as v4) of i3 mega

### Feature Workflow

1.Build for i3 mega with trigorilla-pro board in the IDE
2.Flash the firmware into printer with stm32flash, flash loader demonstrator etc, not with cura etc.
3.Reboot printer normally and the firmware work

#### Additional Information

Steps to flash the trigorilla-pro board can be found here:
https://github.com/napyk/trigorilla-pro

**Comment by DanJunior78** [comment]
The board is not supported from Marlin firmware...i am not sure if @knutwurst want to dig in this rare board, which is anyway born to die, because you can´t change the drivers (i had the same board in my i3 Mega and i´ve changed it last week to an MKS)

**Comment by Blue-Beaker** [comment]
> The board is not supported from Marlin firmware...i am not sure if @knutwurst want to dig in this rare board, which is anyway born to die, because you can´t change the drivers (i had the same board in my i3 Mega and i´ve changed it last week to an MKS)

I have successly compiled marlin 2.0.7 for my i3 mega and worked, just changed some pin defs in the marlin config of trigorilla-pro pinouts.

**Comment by Blue-Beaker** [comment]
and this board need stm32flash etc. with jp1 disconnected (bootloader mode) to flash firmware.

**Comment by knutwurst** [comment]
@Blue-Beaker, did you manage to get the Touchscreen running? Can you use the original Marlin menu? Can you post some Photos? I am also interested in this and I think that's quite interesting for many people out there :)

**Comment by TaylorWatson** [comment]
> The board is not supported from Marlin firmware...i am not sure if @knutwurst want to dig in this rare board, which is anyway born to die, because you can´t change the drivers (i had the same board in my i3 Mega and i´ve changed it last week to an MKS)

Can you link the board you purchased to replace? I also have this board in my Mega-S and want to replace it.

**Comment by DanJunior78** [comment]
There are many possibilities. I've placed a MKS SGen L board with TMC 2209, TFT35 and a LCD 12864... TFT makes not too much sense...in my Mega X I'll put a Robin Nano V2.
I've seen an interesting board from Bigtreetech...they have on the TFT the dual mode, mixed LCD 12864 with TFT funktinalities.
So...there is a big choice if you're not afraid of something like that...in the pictures. Finding out, what goes where...lol this![IMG_20201003_190653_547.jpg](https://user-images.githubusercontent.com/55321080/96933374-9752e280-14c0-11eb-9305-e20566aa4f64.jpg)![IMG_20201004_140248_757.jpg](https://user-images.githubusercontent.com/55321080/96933390-a0dc4a80-14c0-11eb-8625-a49ad046861d.jpg)

**Comment by dimitarpenev** [comment]
Hi Guys, I just bought  Mega-S and got Trigorila V0.0.2 board. 
It is Atmega 2560  based. It is 8 bit AVR with 16MHz clock.
I am very new to the 3D printers. 
Can you let me know what benefits I would get if migrate to the 32 bit 100MHz board you have mentioned above?

**Comment by DanJunior78** [comment]
It's like with anything else...the benefit related to the calculation speed, if there would be something what needs to get heavily calculated. But mainly I did the modification, because I had the 32bit board with fixed drivers. The printer was loud. I couldn't change to LVs or TMCs.
There is also not a big price difference that you won't buy a 32 bit board as replacement then a 8 bit one.

**Comment by dimitarpenev** [comment]
Ok but in terms of printing quality and speed. 
Should I expect any difference (with the current Merlin software) if I upgrade to  MKS SGen L for example
My 8 bit board uses drivers as a separate modules.

**Comment by DanJunior78** [comment]
No, you won't,e.g.my Mega X is still running the stock 8 bit board...and there is no difference,because we can't print on high speeds which needs some more processing power.

**Comment by dimitarpenev** [comment]
Thank you DanJunior78 for letting me know!

**Comment by knutwurst** [comment]
Since the Trigorilla Pro mainboard is more of a niche product in the Mega S, I refrain from installing the support for it, as the effort is much higher than the benefit. Especially since you could and would use the display in "Marlin mode" with real text on the tft.
The Trigorilla Pro is actually used in the Anycubic Predator and there is [already a marlin port for this](https://github.com/SXHXC/Marlin-Anycubic-Predator-Trigorilla-PRO). Actually, this could be rewritten for the Mega S, but that would be a completely new project.

I'm sorry to have to say it, but ... no .. I will not support the 32 bit board with this firmware.
