### ISSUE TITLE
[BUG] (mesh bed leveling next point activated by default with different item selected on LCD)

### ISSUE THREAD

**Issue by weirdgyn** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#273]
### Bug Description

When using the mesh bed leveling feature activated by LCD menu on Anycubic i3 Mega S (Trigorilla 1.0) the _Next leveling point_ command is executed automatically when pushing on the _refresh_ button even if a different option is supposedly selected.

### Steps to Reproduce

1. Access the _Mesh Bed Leveling_ submenu
2. Start mesh bed leveling
3. Select the _Next leveling point_ at least once
4. Confirm with _refresh_ button
5. [The last option on LCD _Up 0.02 mm_ is selected] Confirm with _refresh_ button.

**Expected behavior:**

Printer's head should move up 0.02 mm.

**Actual behavior:**

The _Next leveling point_ command is executed without any Z movement

**Comment by knutwurst** [comment]
This is not a bug that I can fix. The problem is that the display also refreshes the list when you use the refresh button. And then the first element is always selected, whether you like it or not.

The firmware works in such a way that the last(!) point always remains selected. So you can click "UP 0.02" and then click refresh multiple times if you like.

But you have to do this once after "Next Mesh Point", otherwise the next mesh point will be selected each time.

Is stupid I know. But unfortunately there is no other way, because the menu consists of a misused file list.

Best,
Olli

**Comment by weirdgyn** [comment]
ok

**Comment by knutwurst** [comment]
I'm sorry I can't help :/

**Comment by weirdgyn** [comment]
it was not a big issue anyway but I like to give my contribution if possible..
