### ISSUE TITLE
[BUG] Motor-Richtung/direction

### ISSUE THREAD

**Issue by PatrickK1234** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#33]
Hi,
Yesterday I tried flashing to your newest Firmware "MEGA_P_v1.1.7-BETA2" and "MEGA_P_TMC_v1.1.7-BETA2", but neither worked for the Pro-Model. The Issue is that either the original (transparent Anycubig BMG) extruder works the other way around or all other 3-Axis-Movements are reversed.
Using the non-TMC-firmware lets the x/y/z axis perform correctly, but feeding in the filament needs to be done in the printer menu by hitten the retraction button and the other way around. This means that while printing the filament is retracted all the time insted of extruded, so you can't print with the current marlin firmware.
I-ve got the printer beginning of this Month and the original Firmware was 1.2.9 from anycubic, I didn't change a hardware other than the fans. Even with the freshly downloaded 1.2.8 (I don't know why they didn't publish the 1.2.9) from their website the axis and motor direction fits.
I know that the pro model uses TMC drivers as standard, but maybe Anycubic reversed some in the build.

I hope this helps adressing the right movement-directions in your firmeware.
Best regards
Pat

**Comment by knutwurst** [comment]
Hi Pat,
this is known issue which has been fixed [here](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/commit/15dcb2b0d17dce02fdedc240cc4049cdb2684b01). Currently it's only available in the sourcecode, but it comes with the 1.1.7-Release version.

The reason is that I created a KNUTWURST_BMG feature-toggle, which can be enabled for all printers, which inverts the Extruder and sets the feedrate correctly... but I forgot, that the feature is mandatory for the Mega P, so I kinda messed up the inversions.

In the meantime, you could use the 1.1.6, which also supports the Mega Pro.
