### ISSUE TITLE
[FR] Set RESTORE_LEVELING_AFTER_G28

### ISSUE THREAD

**Issue by DunklerPhoenix** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#37]
### Description

If you set RESTORE_LEVELING_AFTER_G28 in Firmware, you don't need M420 S1 anymore.
Wouldn't be this a good idea for your Firmware?

EDIT: Ich hätte auch einfach in Deutsch schreiben können 

```
  .-'---`-.
,'          `.
|             \
|              \
\           _  \
,\  _    ,'-,/-)\
( * \ \,' ,' ,'-)
 `._,)     -',-')
   \/         ''/
    )        / /
   /       ,'-'
```

**Comment by knutwurst** [comment]
English is fine because of the other people who can't speak German :) Github is more international. But German is spoken in the Facebook group ;)

To answer your question: RESTORE_LEVELING_AFTER_G28 is already enabled by default, but it is sometimes ignored or the old values are loaded. 

![Bildschirmfoto 2020-11-12 um 09 00 44](https://user-images.githubusercontent.com/36196269/98911915-aaf0d800-24c5-11eb-89f0-464b0afe014b.jpg)
