### ISSUE TITLE
Change to custom driver type?

### ISSUE THREAD

**Issue by Meganium97** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#379]
I was wondering if I could use multiple types of drivers with this (excluding a4988), I was thinking of trying something like TMC2100 or LV8729 for motion system and DRV8825 for extruder. Would that be possible and how would I set that up within the confines of VSCode?

**Comment by stklcode** [comment]
The driver types are specified in the _Configuration.h_ for each axis.
Default in this FW is `TMC2208_STANDALONE` when a `*_TMC`  variant is built and `A4988` otherwise.

You can mix the divers as required for your hardware.

https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/blob/ac7c27240382b9b3912cebc31fe0031bfa000a06/Marlin/Configuration.h#L225-L286

You probably have to check the invert flags for X/Y/Z/E0 which are curently depending on the target printer and the BMG flag.

https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/blob/ac7c27240382b9b3912cebc31fe0031bfa000a06/Marlin/Configuration.h#L2003-L2008
