### ISSUE TITLE
[Question] Are TMC 2208 v1.2 drivers compatible with linear advance?

### ISSUE THREAD

**Issue by meltiseugen** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#392]
I didn't find the "support" in the issue type, so I don't really know where to post a question tlpther then here

**Comment by Alkerion** [comment]
Use TMC2209 instead and it will works flawlessly.

**Comment by knutwurst** [comment]
Yes and no. 
The drivers are indeed compatible, but require really good cooling and a high Vref on E0.

**Comment by meltiseugen** [comment]
> Use TMC2209 instead and it will works flawlessly.

@knutwurst do I need to make a custom build for the 2209? Or is it compatible with your TMC builds?

**Comment by Alkerion** [comment]
2209 run cooler than 2208, they support more features like LA, so the choice between the two is quickly made.

I use 1.15V and it run flawlessly since months.

Just update your configuration.h and compile.

#if ENABLED(KNUTWURST_TMC)
  #define X_DRIVER_TYPE  TMC2209_STANDALONE
  #define Y_DRIVER_TYPE  TMC2209_STANDALONE
  #define Z_DRIVER_TYPE  TMC2209_STANDALONE
  #define E0_DRIVER_TYPE TMC2209_STANDALONE
  #define E1_DRIVER_TYPE TMC2209_STANDALONE

**Comment by Boostie76** [comment]
> Yes and no. The drivers are indeed compatible, but require really good cooling and a high Vref on E0.

What do you mean by really good cooling? Is the stock fan enough? If not, should I disable LA again?
