### ISSUE TITLE
[BUG] [AI3MS] False Bugfixing?

### ISSUE THREAD

**Issue by Marcv0dka** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#459]
In version 1.4.4, there is a bufixing called _"Fix missing software endstop on Z_MIN."_ 
I think this shouldn't be a fix instead of an feature, because now if I want to mesh level my Anycubic i3 Mega S, I can't go lower than the endstops. The Problem now is, I need to go lower because of Bed shaping!

For example: 
The 4-point leveling is fine, as it should.
Now i want to mesh level the printer. At the right side, the leveling is good! At the left side, the printer should be leveled lower, because of bed shaping. but it can't go lower caused of the Z-Endstops.

![image](https://user-images.githubusercontent.com/46052344/236765169-2f6289f8-a789-41bd-a2b0-0167b665b2b0.png)

In version 1.4.3, this isn't a problem, I can go lower than the endstops in the mesh leveling program. Theoretically I could push the bed down with the nozzle if i want to. in 1.4.4 this isn't possible.
I hope you unterstand what I mean :)

**Comment by knutwurst** [comment]
The value that was previously allowed was actually significantly (factor 10) too large, which is why it was possible to simply break off the limit switches.

The current value protects the limit switches. So it's already a bug fix.

But I'll see if I don't build in a little more tolerance. But if your bed is really THAT crooked, it will be difficult to print with the current printer design.

Sorry.
