### ISSUE TITLE
'disable fil sensor'  did't work 

### ISSUE THREAD

**Issue by Zyp1059872370** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#464]
hello big shot 
i used your 1.5-beta.5 and 1.5-beta.6 (mega_s_dgus_tmc_blt_10) and found the  'disable fil sensor'  did't work .
when i chose it ,the machine display menu tablelist will chenge to blank and then it make a sound like  dididi~
and when i want print something it will pop up prompt "lack of  filament ...." but when i use same version for "mega_s_dgus_tmc" it will not appear this problem.
 
my machine is mega-s 

end Thank you for providing the code,Present my sincere blessings

**Comment by knutwurst** [comment]
Hi,
the code which all printers are using is exactly the same, so the behaviour also should be the same. It might be that the command has not been processed, because some other task wasn't finished at the time. Maybe the filament runout routine? M600 is called and needs to reheat the nozzle, feed new filament and so on.

Just try to power of the printer, disable the sensor and try again.

I own a Mega S with BLT and DGUS clone Display and can confirm that it works :)
