### ISSUE TITLE
[BUG] SD card file list recognition error [ Anycubic Mega X ]

### ISSUE THREAD

**Issue by tgkang43** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#465]
If the SD card is removed and reinserted while the printer is on, an error occurs in recognizing the file list.
( It returns to normal only when the printer is turned off and then back on. )

**Comment by knutwurst** [comment]
What firmware Version? What printer configuration?

**Comment by tgkang43** [comment]
I'm sorry I didn't provide enough information. The firmware used is MEGA_X_DGUS_v1.5.0-RC1.

**Comment by knutwurst** [comment]
I'm on it :)

**Comment by knutwurst** [comment]
It should be fixed in https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/commit/6bc410a0e3e895e0c3b57e74093db7325a3d7110.

To get the fix, you need to [compile the firmware](https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Howto:-Compile-Firmware-with-PlatformIO) or wait til the next release.

**Comment by tgkang43** [comment]
Thank you !
I look forward to the next release.

**Comment by knutwurst** [comment]
Soooo.... since it is fixed, may I close the issue?

**Comment by tgkang43** [comment]
Yes, I will close the issue while waiting for the next version.
