### ISSUE TITLE
[BUG] M593 and M493 commands are unknown

### ISSUE THREAD

**Issue by FOSV** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#485]
After flashing the firmware as per the guide and loading and saving the default values in EEPROM, when I try to print the ringing tower and monitor from console the printer at each layer change it tells me "M593 unknown command."
In fact I do not see any ringing change in the printout that is produced. 
I noticed, also that in the printer information the firmware version remains unchanged and so 1.1.2, from console however I notice that the version has indeed changed.

I have a totally stock Anycubic i3 Mega.

1 - Starting from FW 1.1.2 I flashed your 1.5.2 (file "MEGA_v1.5.2.hex").
2 - Noticing this behavior I tried flashing the most recent original version available on the Anycubic site, 1.1.5. (Strangely, even by flashing the original firmware the version shown on the display by the printer remains 1.1.2, again, however, from the terminal it shows the correct version).
3 - After flashing the original 1.1.5 I proceeded to flash your firmware without getting a resolution to the problem.

**Comment by knutwurst** [comment]
Hi,
First of all I have to tell you that Input Shaping is not activated yet. This is simply because I haven't been able to gain any experience with the configuration and can therefore not offer a finished version. This topic is already discussed in bug ticket #482 and the high RAM consumption in particular is a problem, which is why it is possible that input shaping will never work reliably on a Trigorilla mainboard.

This is the reason why the GCode commands cannot be processed - the feature does not exist (yet).

Regarding the second "problem", I have to tell you that the firmware version of the Anycubic 1.0 display is permanently burned into the display firmware. It doesn't matter whether there is any firmware running on the mainboard at all - the display always shows version 1.1.2.

Only the later displays read the version and can also display it.

I hope your questions have been answered :)
