### ISSUE TITLE
[FR] Can you pls make a Firmware Version fou the Mega X DGUS TMC with Inverted Extruder Motor

### ISSUE THREAD

**Issue by Storma-X** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#516]
Hey, can you make a Firmware for the Mega X with the DGUS Display and the TMC Motors with Inverted Extruder Motor? 

Just like the Normal MEGA_X_DGUS_TMC but only with an inverted Extruder Motor?

**Comment by knutwurst** [comment]
Hey @Storma-X ,
uh... no :) 
You can just invert the extruder step value with the M92 gcode.

`M92 E-396`

Otherwise you can compile the firmware by yourself. See: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/wiki/Howto:-Compile-Firmware-with-PlatformIO

**Comment by Storma-X** [comment]
Hey, where can i change the Value "M92 E-396" in my normal gcode is no Line with M92

**Comment by SirMike3D** [comment]
Hi!
When compiling an own version with inverted extruder, which file(s) and which line(s) have to be modified?
What are the E-Steps for the MEGA-S extruder? I am asking because I have updated my MEGA 1G with the MEGA S extruder upgrade kit and I do not know, if the MEGA S extruder has the same e steps like the old (1G) one.
BR Mike

**Comment by stklcode** [comment]
https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/blob/1ef65dc26ba2d697c6ed1dc0eddc5fbb219d964f/Marlin/Configuration.h#L1378-L1384

89 for the Mega 1G vs.393 for the Mega S
