### ISSUE TITLE
[BUG] Mega S prints off of bed

### ISSUE THREAD

**Issue by Philoneous** [knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S#52]
### Bug Description

I tried to print a bed leveling test with a total size of 210x210mm (5mm skirt distance), I have already changed the bed size in Cura according to the Wiki. There appears to be an offset as the print was ~10mm away from the front of the printbed, resulting in the back of the print not being on the printbed. I am using the Starting G-Code provided in the Wiki

### My Configurations

Your Precompiled MEGA_S_TMC_v1.1.8.hex

### Steps to Reproduce

1. Print 210x210mm object
2. Wait
3. Observe that Print is not on Buildplate :(

**Expected behavior:** Print fully on Buildplate

**Actual behavior:** Print seems to be offset in the Y direction

#### Additional Information

![cura](https://user-images.githubusercontent.com/49252888/104491055-fb71d800-55d1-11eb-82cc-ec054e17a2cc.png)
![printersettings](https://user-images.githubusercontent.com/49252888/104491058-fd3b9b80-55d1-11eb-8b93-e80c6591d192.png)

**Comment by Philoneous** [comment]
Here is a picture of the hotend at z0:
![5088ada5-21d1-47dc-9128-a92993030a27](https://user-images.githubusercontent.com/49252888/104492775-6a503080-55d4-11eb-8bee-e1e5b532d95b.jpg)

**Comment by v-a-d-e-r** [comment]
Same here....

**Comment by frobert** [comment]
Same here, but by my mistake, loaded wrong firmware :/
Maybe you did the same :)

**Comment by knutwurst** [comment]
A Y-offset is theoretically not possible because the zero position is specified by the limit switch. In some cases, however, the limit switch triggers too early or too late. Then the Y-axis shifts and you cannot print on the whole bed.

Anycubic built a tolerance in that the size was severely limited. I only adopted the maximum possible mechanical values in the firmware. However, this assumes that the printer is set correctly.

Check the Y limit switch. Maybe it's not sitting correctly.

**Comment by quattroerik** [comment]
I have the same problem, but additionally with a self designed print head.
Using Home Offset solved the problem for me.
https://marlinfw.org/docs/gcode/M206.html
Don't forget to add G0 X0 Y0 after homing.
